Repository Team-Smeme/Smeme-server, pull requests merged in 2023-01, with the labels that each got.

#7 [INIT] husky 설정 추가
  .gitignore
  .husky/pre-commit
  package-lock.json
  package.json
  yarn.lock
Labels: Unan, ⚙️Setting

#11 CI TEST
  .github/workflows/deploy.yml
  package.json
  src/config/index.ts
  src/index.ts
  yarn.lock
Labels: Sohyeon, ⚙️Setting

#13 [ADD] deploy 관련 파일 추가
  .github/workflows/deploy.yml
  appspec.yml
  scripts/after-deploy.sh
Labels: Sohyeon, ⚙️Setting

#15 [DOCS] README.md 업데이트
  README.md
Labels: Unan, ⚙️Setting

#17 [DOCS] README.md 업데이트
  .github/workflows/deploy.yml
  README.md
Labels: Unan, ⚙️Setting

#20 [ADD] constants 파일 생성
  .gitignore
  src/constants/index.ts
  src/constants/responseMessage.ts
  src/constants/statusCode.ts
  src/constants/tokenType.ts
Labels: Unan, ⚙️Setting

#25 [FEAT] 일기 작성 API 구현
  package.json
  prisma/schema.prisma
  src/controllers/DiaryController.ts
  src/controllers/index.ts
  src/index.ts
  src/interfaces/diary/DiaryRequestDto.ts
  src/routers/DiaryRouter.ts
  src/routers/index.ts
  src/services/DiaryService.ts
  yarn.lock
Labels: Sohyeon, 💻Feature

#34 [FIX] CD TEST 재시도
  .github/workflows/deploy.yml
  package.json
  scripts/after-deploy.sh
  yarn.lock
Labels: Sohyeon, 🐞BugFix

#42 [TEST] CD TEST
  src/index.ts
Labels: Sohyeon, ⚙️Setting

#44 [FIX] 컨벤션 기준으로 코드 수정
  prisma/schema.prisma
  src/controllers/DiaryController.ts
  src/controllers/index.ts
  src/controllers/testController.ts
  src/routers/DiaryRouter.ts
  src/routers/index.ts
  src/routers/testRouter.ts
  src/services/index.ts
  src/services/testService.ts
Labels: Sohyeon

#26 [ADD] 로그인, 회원가입 관련 API 구현
  package.json
  src/config/index.ts
  src/constants/responseMessage.ts
  src/controllers/AuthController.ts
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/interfaces/auth/AuthRequestDto.ts
  src/interfaces/user/UserRequestDto.ts
  src/routers/AuthRouter.ts
  src/routers/UserRouter.ts
  src/routers/index.ts
  src/services/AuthService.ts
  src/services/UserService.ts
  src/services/index.ts
  src/utils/jwtHandler.ts
  src/utils/social.ts
  yarn.lock
Labels: Unan, 📡API

#35 [FEAT] 일기 삭제 API 구현
  src/controllers/DiaryController.ts
  src/interfaces/diary/DiaryRequestDto.ts
  src/routers/DiaryRouter.ts
  src/services/AuthService.ts
  src/services/DiaryService.ts
Labels: Unan, 📡API

#52 [FEAT] 게시판 일기 상세 조회 API 구현
  src/controllers/DiaryController.ts
  src/interfaces/diary/DiaryResponseDto.ts
  src/routers/DiaryRouter.ts
  src/services/DiaryService.ts
Labels: Sohyeon, 📡API

#55 [FEAT] 게시판 일기 조회 API 구현
  src/controllers/DiaryController.ts
  src/interfaces/diary/DiaryResponseDto.ts
  src/routers/DiaryRouter.ts
  src/services/DiaryService.ts
Labels: Sohyeon, 📡API

#58 [FIX] 게시판 일기 상세조회 기능 수정
  src/controllers/DiaryController.ts
  src/interfaces/diary/DiaryResponseDto.ts
  src/services/DiaryService.ts
Labels: Sohyeon, FIX

#36 [FEAT] 내 일기 상세조회 API 구현
  src/constants/responseMessage.ts
  src/controllers/DiaryController.ts
  src/controllers/UserController.ts
  src/interfaces/diary/DiaryRequestDto.ts
  src/routers/DiaryRouter.ts
  src/routers/UserRouter.ts
  src/services/DiaryService.ts
  src/services/UserService.ts
Labels: Unan, 📡API

#66 [FIX] 오타 수정
  src/controllers/DiaryController.ts
Labels: Sohyeon, FIX

#63 [FEAT] 구문 스크랩 API 기능 구현
  src/controllers/ScrapController.ts
  src/controllers/index.ts
  src/interfaces/scrap/ScrapRequestDto.ts
  src/routers/ScrapRouter.ts
  src/routers/index.ts
  src/services/ScrapService.ts
  src/services/index.ts
Labels: Sohyeon, 📡API

#68 [FEAT] 스크랩 목록 조회 API 구현
  src/controllers/ScrapController.ts
  src/interfaces/scrap/ScrapResponseDto.ts
  src/routers/ScrapRouter.ts
  src/services/ScrapService.ts
Labels: Sohyeon, 📡API

#70 [ADD] .env to deploy 파일 반영
  .github/workflows/deploy.yml
  src/config/index.ts
  src/routers/TestRouter.ts
Labels: Sohyeon, ⚙️Setting

#72 [REFACTOR] API express-validator 추가
  src/controllers/AuthController.ts
  src/controllers/DiaryController.ts
  src/controllers/UserController.ts
  src/routers/AuthRouter.ts
  src/routers/DiaryRouter.ts
  src/routers/UserRouter.ts
  src/services/DiaryService.ts
Labels: Unan, 🛠️Refactor

#77 [FIX] 삭제된 service code 추가
  src/services/DiaryService.ts
Labels: Unan, 📡API, FIX

#74 [FEAT] 일기 추천 기능 구현
  src/controllers/DiaryController.ts
  src/interfaces/diary/DiaryLikeDto.ts
  src/routers/DiaryRouter.ts
  src/services/DiaryService.ts
Labels: Sohyeon, 📡API

#80 [FEAT] 카테고리 전체 조회
  src/controllers/CategoryController.ts
  src/routers/CategoryRouter.ts
  src/services/CategoryService.ts
Labels: Sohyeon, 📡API

#83 [REFACTOR] 소셜로그인 api 분기처리 및 컬럼 추가
  src/routers/AuthRouter.ts
  src/services/AuthService.ts
Labels: Unan, 🛠️Refactor, 📡API

#84 [REFACTOR] API auth middleware 추가
  src/middlewares/auth.ts
  src/routers/DiaryRouter.ts
  src/routers/ScrapRouter.ts
  src/routers/UserRouter.ts
Labels: Unan, 🛠️Refactor, 📡API

#86 [CHORE] 내 일기 조회, 목록 조회 시간 포맷 변경
  src/services/UserService.ts
Labels: Unan, 🛠️Refactor, 📡API

#89 [ADD] 카테고리 및 랜덤 주제 빈 값 처리 로직 추가
  src/controllers/UserController.ts
  src/interfaces/diary/DiaryRequestDto.ts
  src/routers/DiaryRouter.ts
  src/services/DiaryService.ts
  src/services/UserService.ts
  src/utils/categoryTopic.ts
Labels: Sohyeon, 🛠️Refactor

#92 [ADD] 카테고리 검색 로직 추가
  src/controllers/DiaryController.ts
  src/services/DiaryService.ts
Labels: Sohyeon, 💻Feature

#94 [ADD] id 필드 추가
  src/interfaces/category/CategoryResponseDto.ts
  src/services/CategoryService.ts
Labels: Sohyeon

#97 [REFACTOR] 일기 수정 API 카테고리, 토픽 관련 수정
  src/controllers/DiaryController.ts
  src/interfaces/diary/DiaryRequestDto.ts
  src/routers/DiaryRouter.ts
  src/services/DiaryService.ts
Labels: Unan, 🛠️Refactor, 📡API

#100 [FIX] 랜덤 주제 조회 및 일기 작성 API, 랜덤 주제 관련 데이터 형식 변경
  prisma/schema.prisma
  src/controllers/CategoryController.ts
  src/interfaces/category/CategoryResponseDto.ts
  src/interfaces/diary/DiaryRequestDto.ts
  src/routers/CategoryRouter.ts
  src/routers/DiaryRouter.ts
  src/services/CategoryService.ts
  src/services/DiaryService.ts
  src/utils/categoryTopic.ts
Labels: Sohyeon, 🐞BugFix

#103 [ADD] 공개여부 조건 추가
  src/services/DiaryService.ts
Labels: Sohyeon, 💻Feature

#110 [REFACTOR] 내 일기 목록 조회 date query 적용
  src/controllers/UserController.ts
  src/interfaces/diary/DiaryResponseDto.ts
  src/services/UserService.ts
Labels: Unan, 🛠️Refactor, 📡API

#115 [CHORE] 소셜로그인 API 수정
  src/controllers/AuthController.ts
  src/utils/jwtHandler.ts
Labels: Unan, 🛠️Refactor, 📡API

#116 [FEAT] 테스트 코드 구현
  .github/workflows/deploy.yml
  package.json
  src/config/index.ts
  test/category.spec.ts
  test/diary.spec.ts
  test/index.spec.ts
  test/scrap.spec.ts
  test/user.spec.ts
Labels: Sohyeon, 💻Feature

#117 [CHORE] 내 일기 상세조회 response에 topicId, topic 추가
  src/services/UserService.ts
Labels: Unan, 🛠️Refactor, 📡API

#119 [ADD] Fixed Access Token 추가
  .github/workflows/deploy.yml
  src/config/index.ts
Labels: Sohyeon, 🛠️Refactor

#122 [REFACTOR] list 조회 API response data 수정
  src/services/DiaryService.ts
  src/services/ScrapService.ts
  src/services/UserService.ts
Labels: Unan, 🛠️Refactor, 📡API

#124 [DOCS] 리드미 최종 수정
  README.md
Labels: documentation, Sohyeon

#126 [FIX] 응답 데이터 수정
  src/controllers/ScrapController.ts
Labels: Sohyeon, FIX

#128 [ADD] 미지정 랜덤주제 일기 조회 이슈 해결
  src/services/DiaryService.ts
Labels: Sohyeon, FIX

#130 [FIX] 조회 이력 생성 예외처리 추가
  prisma/schema.prisma
  src/services/DiaryService.ts
Labels: Sohyeon, 🐞BugFix

#132 [ADD] 리드미에 서비스 소개 이미지 추가
  README.md
Labels: documentation, Sohyeon
